'use client';
import Nav from '@/components/layout/nav'
import './globals.css'
import { Inter } from 'next/font/google'
import AppContextProvider from "@/context/app-context"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
        <header>
        
        </header>
       
       <AppContextProvider>
            {children}
       </AppContextProvider>
      
      {children}
      </body>

    </html>
  )
}
